---
- name: Prepare host that will run the app.
  hosts: app
  become: yes
  become_method: sudo
  vars_files:
    - "{{ config_file }}"
  roles:
    - role: db-user
    - role: target

- name: Prepare MySQL host.
  hosts: db
  become: yes
  become_method: sudo
  vars_files:
    - "{{ config_file }}"
  roles:
    - role: db

- name: Prepare Solr host.
  hosts: solr
  become: yes
  become_method: sudo
  vars_files:
    - "{{ config_file }}"
  roles:
    - role: solr-core
      when: dependency_solr is defined and dependency_solr

- name: Prepare Apache host.
  hosts: web
  become: yes
  become_method: sudo
  vars_files:
    - "{{ config_file }}"
  roles:
    - role: apache-config

