---
- name: Minimal provisioning of Vagrant Box as testing target.
  hosts: vagrant
  remote_user: vagrant
  become: yes
  vars_files: 
    - "{{ config_file }}"
  roles:
    - role: vmock
      vmock_deploy_users: "{{db_deploy_users}}"
      tags: ["testing", "vagrant"]
    - role: zzet.rbenv
      tags: ["testing", "vagrant"]

