---
- name: Create the app's system group
  group:
    gid: "{{user_gid}}"
    name: "{{user_group}}"
    state: present
    system: no

- name: Create the app's system user
  user:
    uid: "{{user_uid}}"
    name: "{{user_name}}"
    group: "{{user_group}}"
    comment: "{{user_comment}}"
    createhome: yes
    home: "{{user_home}}"
    shell: /bin/bash
    state: present
    system: yes

- name: Add deployment users to app group
  user:
    name: "{{item}}"
    append: yes
    groups: "{{user_group}}"
    state: present
  with_items: "{{ user_deploy_users }}"

- name: Install the user's public ssh key
  authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ user_ssh_key }}"
