---
- name: Create the app's system group
  group:
    gid: "{{user_gid}}"
    name: "{{user_group}}"
    state: present
    system: no

- name: Create the app's system user
  user:
    uid: "{{user_uid}}"
    name: "{{user_name}}"
    group: "{{user_group}}"
    comment: "{{user_comment}}"
    createhome: yes
    home: "{{user_home}}"
    shell: /bin/bash
    state: present
    system: yes

- name: Install the user's public ssh key
  authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ user_ssh_key }}"
