---
- name: Check required varaibles
  assert: { that: "item is defined" }
  with_items:
    - puma_svc_rbenv_root
    - puma_svc_deploy_dir
    - puma_svc_app_name

- name: Install application target
  template:
    src: instance.target.j2
    dest: /etc/systemd/system/{{puma_svc_app_name}}.target
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Install puma service
  template:
    src:   puma@instance.service.j2
    dest:  /etc/systemd/system/puma@{{puma_svc_app_name}}.service
    owner: root
    group: root
    mode:  u=rw,g=r,o=r

- name: Install all of the subservice templates
  template:
    src: subservice@instance.service.j2
    dest: /etc/systemd/system/{{item}}@{{puma_svc_app_name}}.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  with_items: "{{puma_svc_subservices}}"

- name: Install sudoers.d template for app-puma service mgmt
  template:
    src:   sudoers.d.j2
    dest: /etc/sudoers.d/{{puma_svc_app_name}}
    owner: root
    group: root
    mode: u=rx,g=r

- name: Reload systemd service files
  shell: systemctl daemon-reload
