- name: Create the database
  mysql_db:
    encoding: utf8
    name: "{{db_name}}"
    state: present

- name: Create the app DB user
  mysql_user:
    name: "{{db_user_name}}"
    password: "{{db_user_password}}"
    host: '%'

- name: Grant table privs to the app DB user
  mysql_user:
    name: "{{db_user_name}}"
    password: "{{db_user_password}}"
    append_privs: yes
    host: "%"
    priv: "{{db_name}}.*:ALL"
    
- name: Grant privileges to deploy users
  mysql_user:
    name: "{{item}}"
    host: "%"
    append_privs: yes
    priv: "{{db_name}}.*:ALL"
  with_items: "{{db_deploy_users}}"

    
