- name: Create the database
  mysql_db:
    encoding: utf8
    name: "{{db_name}}"
    state: present

- name: Create the app DB user
  mysql_user:
    name: "{{db_user_name}}"
    password: "{{db_user_password}}"
    host: '%'

- name: Grant table privs to the app DB user
  mysql_user:
    name: "{{db_user_name}}"
    password: "{{db_user_password}}"
    append_privs: yes
    host: "%"
    priv: "{{db_name}}.*:ALL"
